name: space
version: '0.1.0'
synopsis: Experimental library
description: Experimental web library
category: Web
author: XT
maintainer: e@xtendo.org
copyright: 2017 XT
license: Apache-2.0
github: xtendo-org/space
extra-source-files:
- README.md
library:
  source-dirs: src
  default-extensions:
  - OverloadedStrings
  exposed-modules:
  - Space.Server
  - Space.View
  dependencies:

  - aeson
  - attoparsec
  - base
  - base64-bytestring
  - bytestring
  - cryptonite
  - directory
  - http-date
  - http-types
  - lucid
  - memory
  - network
  - rawfilepath
  - stm
  - template-haskell
  - text
  - unix
  - wai
  - warp
  - yaml

tests:
  space-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - space
